---
name: Catalyst-Plugin-Authentication-Store-HTTP
version: 0.02
author:
  - 'Daisuke Murase <typester@cpan.org>'
abstract: Remote HTTP authentication storage
license: perl
requires:
  Catalyst: 5.30
  Catalyst::Plugin::Authentication: 0.05
  LWP::UserAgent: 0
provides:
  Catalyst::Plugin::Authentication::Store::HTTP:
    file: lib/Catalyst/Plugin/Authentication/Store/HTTP.pm
    version: 0.02
  Catalyst::Plugin::Authentication::Store::HTTP::Backend:
    file: lib/Catalyst/Plugin/Authentication/Store/HTTP/Backend.pm
generated_by: Module::Build version 0.2612
